### ISSUE TITLE
simfinR_get_price_data sometimes leaves out last datapoints

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [msperlin/simfinR#4]
library(simfinR)

id_companies <- 111052 #Apple
id_companies <- 62747 #Amazon
Preise <- simfinR_get_price_data(id_companies , api_key = api_key)

Price-Data for Apple was missing data for the two last days, while Amazon was complete. Today is the 24.05.2021. Data should be there until 21.05.2021
AAPL is only until the 19.05. 
Simfin however shows on its webpage that all data is there. Also the data can be retreived with the "simfinapi"- library. 

Thanks for making the package!

**Comment by msperlin** [comment]
Thanks. I'll have a look as soon as I can.

**Comment by superchordate** [comment]
FWIW I ran this and don't see the error:

```
library(simfinR)

my_api_key = 'your_key_here'

p1 = simfinR_get_price_data(
  #Apple:
  111052, 
  api_key = my_api_key
) %>% 
  filter(!is.na(.$close_adj))

p2 = simfinR_get_price_data(
  #Amazon:
  62747, 
  api_key = my_api_key
) %>% 
  filter(!is.na(.$close_adj))

all(p1$ref_date == p2$ref_date)
# TRUE
```

**Comment by superchordate** [comment]
Oh I just had a thought: might be due to memoise. Your Apple call might be loading a prior cached API call instead of creating a new call, since the API call has not changed. 

@GitHubGeniusOverlord try deleting your cache folder and re-running. 

@msperlin the fix then might be to add a dummy argument to `simfinR_set_fromJSON` or something, that always is the current date. Then on a different date the function will call the API instead of using memoise cache.

**Comment by msperlin** [comment]
@superchordate  I agree. I might have to rewrite the caching system.  I'll add it to issues.
